org: ashwary
app: aws-node-express-api-project
console: true
service: aws-node-express-api-project
frameworkVersion: "3"
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs14.x
  stage: test
  region: ap-south-1
functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
